import HeartBubbles from '@/components/heart-bubbles';
import Head from 'next/head';
export default function Home() {
  return (
    <>
      <Head>
        <title>It&apos;s Valentine&apos;s Day!</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/love.ico' />
      </Head>
      <HeartBubbles />
      <div className='container'>
        <div className='card card0'>
          <div className='border'>
            <h2></h2>
          </div>
        </div>
      </div>
    </>
  );
}
